apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      initContainers:
      - name: superset-init
        image: binukx/superset-clickhouse:v1
        command: ["/bin/sh", "-c"]
        args:
          - |
            superset db upgrade &&
            superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin123 &&
            superset init
        env:
        - name: SUPERSET_SECRET_KEY
          value: "newEventPlatform2026SuperSecretKey"
      containers:
      - name: superset
        image: binukx/superset-clickhouse:v1
        command: ["/bin/sh", "-c"]
        args:
          - "superset run -h 0.0.0.0 -p 8088 --with-threads"
        ports:
        - containerPort: 8088
        env:
        - name: SUPERSET_SECRET_KEY
          value: "newEventPlatform2026SuperSecretKey"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: analytics
spec:
  selector:
    app: superset
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
  type: LoadBalancer